###
GET http://localhost:8080/exam/java/add?question=q1&answer=a1

###
GET http://localhost:8080/exam/java/add?question=q2&answer=a2

###
GET http://localhost:8080/exam/java/add?question=q3&answer=a3

###
GET http://localhost:8080/exam/java/add?question=q4&answer=a4

###
GET http://localhost:8080/exam/java/add?question=q5&answer=a5

###
GET http://localhost:8080/exam/java/add?question=q6&answer=a6

###
GET http://localhost:8080/exam/java

###
GET http://localhost:8080/exam/java/remove?question=q2&answer=a2

###
GET http://localhost:8080/exam/get/2